#!/usr/bin/env bash
# This script displays "Best School" 9 times and on the 10th time displays "Hi" 
i=1
while [ "$i" -lt 10 ]
do
    echo "Best School"
    if [ "$i" -eq 4 ]; then
        echo "bad luck"

    elif [ "$i" -eq 8 ]
    then
        echo "good luck"
    fi
    i=$((i+1))
done
