#!/usr/bin/env bash
# This script displays "Best School" 20 times and on the 4th and 8th time displays "bad luck from China" and "good luck from Japan"
i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
        4)
            echo "bad luck from China"
            ;;
        8)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
    esac
    i=$((i+1))
done
